spring:
  application:
    name: spring-boot-producer
  data:
    mongodb:
      database: spring-boot-producer

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring-boot-consumer.ribbon.listOfServers: http://localhost:8000/
micronaut-consumer.ribbon.listOfServers: http://localhost:8002/
ribbon.ReadTimeout: 100000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100
          thread:
            timeoutInMilliseconds: 100000