spring:
  application:
    name: spring-boot-consumer
  data:
    mongodb:
      database: spring-boot-consumer

server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

kafka:
  server: localhost:9092
  group:
    id: server.broadcast
  producer:
    id: producer